name = "Coder"
license = "MIT"
licenselink = "https://github.com/juggernautjp/hugo-coder-ja/blob/master/LICENSE.md"
description = "A fork of coder theme, which is a simple blog theme for Hugo, for Japanese language"
homepage = "https://github.com/juggernautjp/hugo-coder-ja"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "juggernautjp"
homepage = "https://juggernautjp.github.io"
